2020-01-06 13:44:07,055 ERROR: Exception on /BrownsvilleTRCclean [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\indexes\base.py", line 4381, in get_value
    return libindex.get_value_box(s, key)
  File "pandas\_libs\index.pyx", line 52, in pandas._libs.index.get_value_box
  File "pandas\_libs\index.pyx", line 48, in pandas._libs.index.get_value_at
  File "pandas\_libs\util.pxd", line 113, in pandas._libs.util.get_value_at
  File "pandas\_libs\util.pxd", line 98, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BrownsvilleTRCclean.py", line 324, in upload_BrownsvilleTRCclean
    data_xls['Tester Tester'] = data_xls.apply(lambda x: TesterTester(x['HRA Release Tester'],x['Housing Type Tester'],x['Housing Level Tester'],x['Building Case Tester'],x['Referral Tester'],x['Rent Tester'],x['Unit Tester'],x[ 'Regulation Tester'],x['Subsidy Tester'],x['Years in Apartment Tester'],x['Language Tester'],x['Posture Tester'],x['Income Verification Tester'],x['PA Tester'],x['Case Number Tester'],x['Housing Activity Tester'],x['Housing Services Tester'],x['Outcome Tester']),axis=1)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\frame.py", line 6487, in apply
    return op.get_result()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\apply.py", line 151, in get_result
    return self.apply_standard()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\apply.py", line 257, in apply_standard
    self.apply_series_generator()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\apply.py", line 286, in apply_series_generator
    results[i] = self.f(v)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BrownsvilleTRCclean.py", line 324, in <lambda>
    data_xls['Tester Tester'] = data_xls.apply(lambda x: TesterTester(x['HRA Release Tester'],x['Housing Type Tester'],x['Housing Level Tester'],x['Building Case Tester'],x['Referral Tester'],x['Rent Tester'],x['Unit Tester'],x[ 'Regulation Tester'],x['Subsidy Tester'],x['Years in Apartment Tester'],x['Language Tester'],x['Posture Tester'],x['Income Verification Tester'],x['PA Tester'],x['Case Number Tester'],x['Housing Activity Tester'],x['Housing Services Tester'],x['Outcome Tester']),axis=1)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\indexes\base.py", line 4389, in get_value
    raise e1
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\indexes\base.py", line 4375, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\_libs\index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ('PA Tester', 'occurred at index 23')
2020-01-06 13:44:33,979 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 13:47:26,553 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 13:51:19,136 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 13:51:57,493 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 14:10:57,553 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 14:15:29,936 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 14:16:46,272 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 14:16:57,509 ERROR: Exception on /BrownsvilleTRCclean [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BrownsvilleTRCclean.py", line 297, in upload_BrownsvilleTRCclean
    data_xls['SS # Tester'] = data_xls.apply(lambda x: SSNum(x['Social Security #']), axis=1)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\frame.py", line 6487, in apply
    return op.get_result()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\apply.py", line 151, in get_result
    return self.apply_standard()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\apply.py", line 257, in apply_standard
    self.apply_series_generator()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\apply.py", line 286, in apply_series_generator
    results[i] = self.f(v)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BrownsvilleTRCclean.py", line 297, in <lambda>
    data_xls['SS # Tester'] = data_xls.apply(lambda x: SSNum(x['Social Security #']), axis=1)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BrownsvilleTRCclean.py", line 283, in SSNum
    FirstDash = CaseNum[3]
IndexError: ('string index out of range', 'occurred at index 28')
2020-01-06 14:17:43,812 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 14:18:56,852 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 15:12:46,419 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 15:48:31,062 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2020-01-06 15:52:44,640 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
