2019-12-30 15:08:26,241 ERROR: Exception on /BoroughSplitter [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 64, in split_by_borough
    worksheet=writer.sheets['Sheet1']
KeyError: 'Sheet1'
2019-12-30 15:09:00,836 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:11:59,275 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:13:18,975 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:14:38,393 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:15:08,933 ERROR: Exception on /BoroughSplitter [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 32, in split_by_borough
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 32, in <lambda>
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
TypeError: 'float' object is not subscriptable
2019-12-30 15:15:20,610 ERROR: Exception on /BoroughSplitter [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 32, in split_by_borough
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 32, in <lambda>
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
TypeError: 'float' object is not subscriptable
2019-12-30 15:15:25,138 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:18:28,479 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:25:38,504 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:25:43,932 ERROR: Exception on /BoroughSplitter [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 38, in split_by_borough
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 38, in <lambda>
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
TypeError: 'NoneType' object is not subscriptable
2019-12-30 15:26:21,249 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
2019-12-30 15:26:24,748 ERROR: Exception on /BoroughSplitter [POST] [inC:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 38, in split_by_borough
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
  File "C:\Users\jackley\Python\Python37-32\venv\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "C:\Users\jackley\Python\GitPython\hyperlinker\app\BoroughSplitter.py", line 38, in <lambda>
    last7 = data_xls['Matter/Case ID#'].apply(lambda x: x[3:])
TypeError: 'NoneType' object is not subscriptable
2019-12-30 15:29:13,956 INFO: Microblog startup [inC:\Users\jackley\Python\GitPython\hyperlinker\app\__init__.py:66]
